version: '3.7'
services:
  server:
    image: shmopen/code-push-server:latest
    volumes:
      - data-storage:/data/storage
      - data-tmp:/data/tmp
    environment:
      DOWNLOAD_URL: 'http://YOUR_MACHINE_IP:3000/download'
      TOKEN_SECRET: 'YOUR_JWT_TOKEN_SECRET'
      RDS_HOST: 'mysql'
      RDS_USERNAME: 'codepush'
      RDS_PASSWORD: '123456'
      RDS_DATABASE: 'codepush'
      STORAGE_DIR: '/data/storage'
      DATA_DIR: '/data/tmp'
      NODE_ENV: 'production'
      REDIS_HOST: 'redis'
      LOCALE: 'cn'
    ports:
      - '3000:3000'
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:latest
    volumes:
      - data-mysql:/var/lib/mysql
      - ./sql/codepush-all-docker.sql:/docker-entrypoint-initdb.d/codepush-all.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'On'
  redis:
    image: redis:latest
    volumes:
      - data-redis:/data
volumes:
  data-storage:
  data-tmp:
  data-mysql:
  data-redis:
